# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pileup_core <- function(gr, bampath, mapqual = 0L, binsize = 1L, shift = 0L, ss = FALSE, maxgap = 16385L) {
    .Call('bamsignals_pileup_core', PACKAGE = 'bamsignals', gr, bampath, mapqual, binsize, shift, ss, maxgap)
}

coverage_core <- function(gr, bampath, mapqual = 0L, maxgap = 16385L) {
    .Call('bamsignals_coverage_core', PACKAGE = 'bamsignals', gr, bampath, mapqual, maxgap)
}

